# Generated by Django 4.1 on 2023-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_something',
            field=models.BooleanField(default=False),
        ),
    ]
